# Generated by Django 2.1.4 on 2019-04-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=10)),
                ('text_field', models.TextField()),
                ('int_field', models.IntegerField()),
                ('file_field', models.FileField(upload_to='')),
                ('image_field', models.ImageField(upload_to='')),
                ('uuild_field', models.UUIDField()),
                ('url_field', models.URLField()),
                ('email_field', models.EmailField(max_length=254)),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=2)),
                ('float_field', models.FloatField()),
                ('date_time_field', models.DateTimeField()),
                ('boolean_field', models.BooleanField()),
                ('fk_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk', to='testapp.RelationClass')),
                ('m2m_field', models.ManyToManyField(related_name='m2m', to='testapp.RelationClass')),
                ('o2o_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='o2o', to='testapp.RelationClass')),
            ],
        ),
    ]
